version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'â¬†ï¸ deps:'
      prefix-development: 'â¬†ï¸ğŸ”¨ dev-deps:'
    assignees:
      - "shanpriyan"
    reviewers:
      - "shanpriyan"
    open-pull-requests-limit: 10
    rebase-strategy: auto
