---
relay:
  upstream: "http://host.docker.internal:8888/"
  host: 0.0.0.0
  port: 3000
logging:
  level: INFO
  enable_backtraces: false
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "sentry_kafka:9093"}
  redis: redis://sentry_redis:6379
