---
relay:
  upstream: 'http://host.docker.internal:8000/'
  host: 0.0.0.0
  port: 7899
logging:
  level: INFO
  enable_backtraces: false
limits:
  shutdown_timeout: 0
processing:
  enabled: true
  kafka_config:
    - {name: 'bootstrap.servers', value: 'sentry_kafka:9093'}
    # The maximum attachment chunk size is 1MB. Together with some meta data,
    # messages will never get larger than 2MB in total.
    - {name: 'message.max.bytes', value: 2097176}
  redis: redis://sentry_redis:6379
