name: bump sentry race

# Serializes the execution of this workflow.
concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - bukzor/bump-sentry-race

defaults:
  run:
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    shell: bash --noprofile --norc -eo pipefail -ux {0}

jobs:
  bump-sentry-race:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
        with:
          # For getsentry/bin/bump-sentry, sentry needs to be at ../sentry relative to getsentry.
          path: sentry

      - name: checkout getsentry
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
        with:
          repository: 'getsentry/getsentry'
          path: getsentry
          # This PAT (Personal Access Token) belongs to getsentry-bot,
          # who can write to getsentry and is SAML+SSO ready.
          token: ${{ secrets.BUMP_SENTRY_TOKEN }}

      - name: bump-sentry-race ${{ github.sha }}
        run: |
          cd getsentry

          python -S -m bin.bump_sentry ${{ github.sha }}

          : forcing the race {
          git reset --hard HEAD^
          date > date.txt
          git add date.txt
          git commit date -m 'bump-sentry-race: forcing the race'
          : } forcing the race

          # If getsentry is pushed to by any other means while we were here,
          # we won't be able to push.
          for i in 1 2 3 4 5; do
              git push origin bukzor/bump-sentry-race && exit 0
              # There's a little bit of network delay here that suffices
              # as a small sleep.
              git pull --rebase origin bukzor/bump-sentry-race
          done

          # 5th and final attempt.
          git push origin master
