# Add a GitHub Check to commits in "master" that specifies the "type" of files that were changed
# ex: "only frontend", "only backed", or "fullstack"
name: meta(deploy)

on:
  push:
    branches:
      - master

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Check for file changes
        uses: getsentry/paths-filter@master
        id: changes
        with:
          list-files: shell
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Create GitHub job
        uses: actions/github-script@v5
        with:
          script: |
            require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/deploy`).updateChangeType({
              github,
              context,
              fileChanges: ${{ toJson(steps.changes.outputs) }}
            });
