name: migrations
on: pull_request

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  did-migration-change:
    name: check if any migration changes
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      added: ${{ steps.changes.outputs.migrations_added }}
      modified: ${{ steps.changes.outputs.migrations_modified }}
    steps:
      - name: Checkout sentry
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e  # v2

      - name: Match migration files
        uses: getsentry/paths-filter@66f7f1844185eb7fb6738ea4ea59d74bb99199e5  # v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  modified-migration:
    name: check if modified migration
    runs-on: ubuntu-20.04
    timeout-minutes: 4
    needs: did-migration-change
    if: needs.did-migration-change.outputs.modified == 'true'

    steps:
      - name: Failure because of modified migration
        shell: bash
        run: |
          echo "If you have a valid reason to modify a migration please get approval"
          echo "from @getsentry/owners-migrations, then ask a Github admin to merge." && exit 1

  sql:
    name: Generate SQL
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    strategy:
      matrix:
        pg-version: ['9.6']

    needs: did-migration-change
    if: needs.did-migration-change.outputs.added == 'true'

    steps:
      # Checkout master to run all merged migrations.
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e  # v1
        with:
          ref: master

      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        id: setup
        with:
          pg-version: ${{ matrix.pg-version }}

      - name: Apply migrations
        run: |
          sentry upgrade --noinput

      # Checkout the current ref
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e  # v1
        with:
          clean: false

      - name: Get changed migration files
        id: file
        run: |
          echo $(git diff --diff-filter=A --name-only origin/master HEAD)
          echo "added=$(git diff --diff-filter=A --name-only origin/master HEAD | grep 'src/sentry/migrations/')" >> "$GITHUB_OUTPUT"

      - name: Generate SQL for migration
        uses: getsentry/action-migrations@f1dc34590460c0fe06ec11c00fec6c16a2159977  # main
        env:
          SENTRY_LOG_LEVEL: ERROR
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          migration: ${{ steps.file.outputs.added }}
