name: migrations
on: pull_request

jobs:
  did-migration-change:
    name: check if any migration changes
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    # Map a step output to a job output
    outputs:
      added: ${{ steps.changes.outputs.migrations_added }}
      modified: ${{ steps.changes.outputs.migrations_modified }}
    steps:
      - name: Checkout sentry
        uses: actions/checkout@v2

      - name: Match migration files
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  modified-migration:
    name: check if modified migration
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    needs: did-migration-change
    if: ${{ needs.did-migration-change.outputs.modified == 'true' }}

    steps:
      - name: Failure because of modified migration
        shell: bash
        run: |
          echo "If you have a valid reason to modify a migration please get approval"
          echo "from @getsentry/owners-migrations, then ask a Github admin to merge." && exit 1

  sql:
    name: Generate SQL
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    strategy:
      matrix:
        python-version: [3.8.12]
    needs: did-migration-change
    if: ${{ needs.did-migration-change.outputs.added == 'true' }}

    steps:
      # Checkout master to run all merged migrations.
      - uses: actions/checkout@v1
        with:
          ref: master

      - name: Setup sentry env (python ${{ matrix.python-version }})
        uses: ./.github/actions/setup-sentry
        id: setup
        with:
          python-version: ${{ matrix.python-version }}
          pip-cache-version: ${{ secrets.PIP_CACHE_VERSION }}

      - name: Apply migrations
        run: |
          sentry upgrade --noinput

      # Checkout the current ref
      - uses: actions/checkout@v1
        with:
          clean: false

      - name: Get changed migration files
        id: file
        run: |
          echo $(git diff --diff-filter=A --name-only origin/master HEAD)
          echo "::set-output name=added::$(git diff --diff-filter=A --name-only origin/master HEAD | grep 'src/sentry/migrations/')"

      - name: Generate SQL for migration
        uses: getsentry/action-migrations@main
        env:
          SENTRY_LOG_LEVEL: ERROR
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          migration: ${{ steps.file.outputs.added }}
