name: openapi
on:
  push:
    branches:
      - master

# hack for https://github.com/actions/cache/issues/810#issuecomment-1222550359
env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3

jobs:
  build_and_deref_json:
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    steps:
      - name: Getsentry Token
        id: getsentry
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7

      - name: Check for python file changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        with:
          mode: migrations
        if: steps.changes.outputs.api_docs == 'true'

      - name: Checkout getsentry/sentry-api-schema
        if: steps.changes.outputs.api_docs == 'true'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
        with:
          ref: 'main'
          repository: getsentry/sentry-api-schema
          path: sentry-api-schema
          token: ${{ steps.getsentry.outputs.token }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        if: steps.changes.outputs.api_docs == 'true'
        id: setup-node
        with:
          node-version-file: '.node-version'

      - uses: pnpm/action-setup@36de12bed180fa130ed56a35e7344f2fa7a820ab # v4

      - name: Build OpenAPI Derefed JSON
        if: steps.changes.outputs.api_docs == 'true'
        run: |
          make build-api-docs

      - name: Build RPC method schema
        if: steps.changes.outputs.api_docs == 'true'
        run: |
          sentry rpcschema > rpc_method_schema.json

      - name: Copy artifacts into getsentry/sentry-api-schema
        if: steps.changes.outputs.api_docs == 'true'
        run: |
          cp tests/apidocs/openapi-derefed.json sentry-api-schema
          cp src/sentry/apidocs/api_ownership_stats_dont_modify.json sentry-api-schema
          cp rpc_method_schema.json sentry-api-schema

      - name: Git Commit & Push
        uses: stefanzweifel/git-auto-commit-action@0049e3fa4059ca715255fbbcb7dea4516f02ce0a # v4.15.3
        if: steps.changes.outputs.api_docs == 'true'
        with:
          repository: sentry-api-schema
          branch: main
          commit_message: Generated
          commit_user_email: bot@getsentry.com
          commit_user_name: openapi-getsentry-bot
