name: openapi

on:
  push:
    branches:
      - master

jobs:
  deref_json:
    runs-on: ubuntu-latest
    steps:
    - name: Getsentry Token
      id: getsentry
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.SENTRY_INTERNAL_APP_ID }}
        private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

    - name: Checkout getsentry/sentry
      uses: actions/checkout@v2
      with:
        path: sentry

    - name: Checkout getsentry/sentry-api-schema
      uses: actions/checkout@v2
      with:
        ref: 'main'
        repository: getsentry/sentry-api-schema
        path: sentry-api-schema
        token: ${{ steps.getsentry.outputs.token }}

    # Install/setup node
    - uses: volta-cli/action@v1

    - name: Build OpenAPI Derefed JSON
      run: |
        cd sentry
        yarn install --frozen-lockfile
        yarn run build-derefed-docs sentry/api-docs/openapi-derefed.json

    - name: Copy artifact into getsentry/sentry-api-schema
      run: |
        cp sentry/api-docs/openapi-derefed.json sentry-api-schema

    - name: Git Commit & Push
      run: |
        cd sentry-api-schema
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name openapi-getsentry-bot
          git config user.email bot@getsentry.com
          git add .
          git commit -m "generated"
          git push origin main
        else
          echo "no changes";
        fi
