name: openapi

on:
  pull_request:
    branches:
      - master

jobs:
  deref_json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout getsentry/sentry
      uses: actions/checkout@v2
      with:
        path: sentry

    - name: Checkout getsentry/sentry-api-schema
      uses: actions/checkout@v2
      with:
        ref: 'main'
        repository: getsentry/sentry-api-schema
        path: sentry-api-schema

    # Install/setup node
    - uses: volta-cli/action@v1

    - name: Build OpenAPI Derefed JSON
      run: |
        cd sentry
        yarn run build-derefed-docs

    - name: Copy artifact into getsentry/sentry-api-schema
      run: |
        cp /sentry/api-docs/api-schema.json /sentry-api-schema

    - name: Git Commit & Push
      run: |
        cd sentry-api-schema
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
